### PR TITLE
Fix InvalidSequenceToken in CloudWatch Logs

### LINKED ISSUE #168: Cloudwatch HTTP error: invalid sequence token
When running a command on a client's sandbox we get the following Warning:
```
Warning: Error executing "PutLogEvents" on "https://logs.us-east-1.amazonaws.com"; AWS HTTP error: Client error: `POST https://logs.us-east-1.amazonaws.com` resulted in a `400 Bad Request` response:
{"__type":"InvalidSequenceTokenException","expectedSequenceToken":"49605576650224253646933900996881587352498596412622676 (truncated...)
 InvalidSequenceTokenException (client): The given sequenceToken is invalid. The next expected sequenceToken is: 49605576650224253646933900996881587352498596412622676434 - {"__type":"InvalidSequenceTokenException","expectedSequenceToken":"49605576650224253646933900996881587352498596412622676434","message":"The given sequenceToken is invalid. The next expected sequenceToken is: 49605576650224253646933900996881587352498596412622676434"} in /usr/src/app/vendor/altis/cloud/inc/cloudwatch_logs/namespace.php on line 54```

### PR DESCRIPTION
**Pull request by joehoyle**
In cases when the sequence token in the cache is wrong, we can auto-retry with the new sequence token.

I also added unit tests here, which I'm running from the main platform-dev repo. I will share my approach on that, but in the mean time I don't see an issue per-say with including the unit tests already.

Fixes #168.

### CODE REVIEW

File: tests/class-test-cloudwatch-logs.php [hunk 1]
```diff
@@ -0,0 +1,57 @@
+<?php
+
+namespace Altis\Cloud\Tests;
```
Comment (joehoyle) [inline tests/class-test-cloudwatch-logs.php:3]: Sorry what?

Comment (roborourke) [reply tests/class-test-cloudwatch-logs.php:3]: Weird. I think you just add `phpcs:disable HM.Files.NamespaceDirectoryName.NameMismatch` for now. Seems like maybe a bug.

**Review by roborourke — APPROVED** [review]

File: tests/class-test-cloudwatch-logs.php (hunk 1 above)
Comment (rmccue) [reply tests/class-test-cloudwatch-logs.php:3]: I think this is from an old version of the coding standards that did some `substr()` wrong, I think we fixed this?

**Review by rmccue — APPROVED** [review]

**Comment by rmccue** [comment]
Do we know what causes these in the first place btw?

**Comment by joehoyle** [comment]
Pretty sure it's due to races between processes.
